### ISSUE TITLE
插件有个bug

### ISSUE THREAD

**Issue by gyh9711** [jae-jae/QueryList-Rule-Baidu#1]
public static function install(QueryList $querylist, ...$opts)
    {
        $name         = $opt[0] ?? 'BingSearcher';
        $bingSearcher = new BingSearcher($querylist);
        $querylist->bind($name, function () use ($bingSearcher) {
            return $bingSearcher;
        });
    }

见上面： $opts,  $name中引用是$opt

**Comment by jae-jae** [comment]
确实是个bug,不过你提错项目了，必应搜索插件是这个项目：https://github.com/liesauer/QLPlugin-BingSearcher
